dist: xenial
os: linux
language: python
python:
  - 2.7

install:
  pip install flake8

script:
  - flake8
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ -n "${TRAVIS_TAG}" ]; then
      ./build.sh
    fi

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file: build/*.zip
  skip_cleanup: true
  on:
    tags: true